### ISSUE TITLE
Nodes of courses still showing

### ISSUE THREAD

**Issue by simoneidenskog-kmh** [moodleuulm/moodle-local_boostnavigation#1]
Hi!

and thanks for a great work! When I'm using the plugin (version 3.2.1) it's possible to hide Calendar and Private files. When I'm trying to hide My courses, the main node "My courses" disappears but still the courses are showing.

In the screenshot, I'm enrolled in three courses: "Musikproduktion 2 (EG1004); "Självständigt arbete (ämnesdidaktik), KPU (FG1300)"; simoneidenskogtest

Regards
/Simon

Screenshot:
![screenshot1](https://cloud.githubusercontent.com/assets/26341428/23821682/9470ca98-063a-11e7-9075-c5475d6439a3.png)

Settings:
<img width="783" alt="settings" src="https://cloud.githubusercontent.com/assets/26341428/23821680/83c6c648-063a-11e7-9e4d-bccb32d9aeaf.png">

Screenshot with nothing checked:
![screnshotnoothing](https://cloud.githubusercontent.com/assets/26341428/23821683/acfe383e-063a-11e7-8844-39004061e28a.png)

**Comment by abias** [comment]
Hi Simon,

thanks for your issue report.

I tried to reproduce the issue and saw that if I activate the setting navshowmycoursecategories on /admin/settings.php?section=navigation, then I have a similar result (Mycourses node is removed, but not the course nodes).

Could you please confirm if you also have this setting enabled and if the course nodes also disappear on your site as soon as you disable this setting? I will then try to find a workaround and submit a patch.

Thanks,
Alex

**Comment by abias** [comment]
Hi Simon,

this is now solved with b5068cda8c186e436977c8ae2c1d9724abcf0bc4.

Thanks,
Alex
