### ISSUE TITLE
Add course admin node to courses nodes

### ISSUE THREAD

**Issue by jrm-unamur** [moodleuulm/moodle-local_boostnavigation#10]
Hi there, 
Many teachers in my institution ask for an access to course admin page from the navdrawer (one clic less than through the course gear icon)
What do you think?
Cheers

**Comment by abias** [comment]
Hi jrm-unamur,

we were able to implement this request during the moodle-dach.eu DevCamp in Zurich yesterday.

With the latest changes in Release v3.4-r4, you will be able to add a link pointing to /course/edit.php?id={courseid}.

Cheers, 
Alex

**Comment by cellule-tice** [comment]
Great Alex,
Thanks a lot
Cheers
Jean-Roch
