### ISSUE TITLE
Custom course node cannot link to main course page 

### ISSUE THREAD

**Issue by pkgh** [moodleuulm/moodle-local_boostnavigation#100]
I have found that the course's URL when entered as a link into a node in insertcustomcoursenodesusers upsets the BNF layout and behaviour: it becomes impossible to switch between courses, the active menu items highlight inconsistently, the course menu items become missing etc.

The node's link must NOT use "/course/view.php?id={courseid}" (which I tried to emulate the default behaviour of the built-in nodes such as "Activities" ) . As a workaround, any other link, such as /course/admin.php?courseid={courseid} , can be used.

My example (Moodle 3.9.8. and BNF v3.9-r6 2020112303):

Tools|/course/view.php?id={courseid}|en||editingteacher,teacher,student|admin,manager|OR||coursetools_en
- Question bank|/question/edit.php?courseid={courseid}|en||editingteacher|admin,manager|OR|fa-question
...

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
