### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by dennis2menace** [moodleuulm/moodle-local_boostnavigation#101]
Hi, our users are quiete happy with the plugin, so after changing from the adaptable theme to boost, they have a good navigation now. But there´s something missing: The activities. Is there a possibility to add the activities to the course navigation? The advantage would be to get a navigation from the course from main page up to the activities at one place
![Bildschirmfoto 2021-11-05 um 10 30 19](https://user-images.githubusercontent.com/70981920/140490487-d8557cd7-8e17-486b-88ad-9bc0355b693a.jpg)
!

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
