### ISSUE TITLE
3.9 - change filters keeps inside the navigation when loading the site with collabsed course navigation

### ISSUE THREAD

**Issue by dennis2menace** [moodleuulm/moodle-local_boostnavigation#102]
![Bildschirmfoto 2021-11-05 um 10 27 56](https://user-images.githubusercontent.com/70981920/140490646-04981f6f-a261-434b-9ff7-de4986b25b8a.jpg)

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
