### ISSUE TITLE
Moodle 4.0 

### ISSUE THREAD

**Issue by ecottis** [moodleuulm/moodle-local_boostnavigation#112]
Hi

I was wondering if you had a timeline for the development of Boost navigation fumbling for Moodle V 4.0 .  I find this really useful plugin that has given me a lot of control of the menu and the ability to hide the Home Page and add common tasks.  I have tried an install on 4.0 but find a lot of the functionality is not yet recognized. 

Thanks for a great plugin.

**Comment by abias** [comment]
local_boostnavigation for Moodle 3.x was mainly built to be able to change the Moodle navigation drawer. Now, on Moodle 4.0, the navigation drawer in its original form is simply not there anymore and many things which this plugin has fiddled with before work differently now.

Against this background, this plugin got a lower priority for our Moodle 4.0 upgrades. However, we are still keen to examine what can and should be done on Moodle 4.0 with local_boostnavigation again.

It would be great if you could add your thoughts which feature of local_boostnavigation 3.x you would like to see ported over to 4.0.

**Comment by ecottis** [comment]
There are a few things that would be useful:

- The ability to remove home, dashboard and courses page, from top menu navigation
- Add my to left draw above the course navigation menu (this would allow improved navigation between courses.)
- Insert custom course nodes to Boost's nav drawer
- Insert custom bottom nodes to left drawer

![image](https://user-images.githubusercontent.com/67025862/184722934-032341f6-5efc-4289-a026-f5731ca4fb6f.png)

Note as you can see I have made some modification but the above would make things a little easier.  I have also adapted the new My courses page so I can now insert blocks as this was a static page in 4.0 not sure why.  Maybe this could be an added feature as I find it useful, but as I directy edited the page code maybe outside of this project. 

Hope this help I’m sure others will have more ideas. 
Regards

Eddie

**Comment by pkgh** [comment]
Hi, I'd vote for such features in a customised / tweaked course-index (or a sticky "block" above it) in Moodle 4:

1) display course (short) name (possibly truncated to first n / customisable characters) next to / below / above the close course-index X button - cf. this tracker https://tracker.moodle.org/browse/MDL-73505, where I'm not sure any work will be done in the Moodle core :/
2) (Below the X link and) before the course-index TOC links  - a (sticky) collapsible node with course-level custom links with placeholders allowed (in Moodle 3 we are using that to point user to their course profiles with a single click, for example)
3) Activities node (collapsible) - with all the activity types grouped by category - again ideally a sticky preceding the the course-index.

As before, the possibility to use filters based on role, cohort, language etc., would be great.

We are not moving to Moodle 4 this year yet, but waiting for the new version to mature, but such are my proposals based on what it is now.
Kind regards.

**Comment by pkgh** [comment]
PS. Will also be testing https://moodle.org/plugins/theme_boost_union , of course. :)

**Comment by ghost** [comment]
Is there any timeline when Boost navigation fumbling for Moodle V 4.0 is published?

**Comment by pkgh** [comment]
PS. Another idea - the option to add custom links associated with the course and user would be great - for example we created menu shortcuts in this way for pages such as:
- course notes: /notes/index.php?course={courseid}
- groups: /group/overview.php?id={courseid}
- my course profile: /user/view.php?id={userid}&course={courseid}

Very useful.
HTH & thanks.

**Comment by michael-milette** [comment]
Hi @abias ,

Any thoughts on when a Moodle 4.x version might become available?

Best regards,

Michael Milette

**Comment by katcee** [comment]
I would also like to continue using this on 4.1. Most specifically to collapse all course nodes automatically when a user enters a course. I don't understand why they set it as default open. But anyway, also some of the features mentioned above are useful, like being able to remove home notes and other menu items or add custom items in the course menu or above it. Thank you :)

**Comment by pkgh** [comment]
BTW - cf. https://tracker.moodle.org/browse/MDL-71212 ("Add course kebab
menu with 'Collapse all' and 'Expand all' options to course index").

**Comment by abias** [comment]
Thank you very much for your very valueable input in this issue!

However, I am somehow sad to write that this plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you again to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set already and is actively maintained and extended. We also plan to add more and more of local_boostnavigation's previous features to Boost Union, but we have finally decided to primarily spend our time to improve Boost Union and not to create a separate toolbox plugin like local_boostnavigation anymore. Thank you for your understanding.

Against this background, I will close this issue.
