### ISSUE TITLE
Boost navigation fumbling

### ISSUE THREAD

**Issue by stephen-livesey** [moodleuulm/moodle-local_boostnavigation#115]
Hi @abias  - are there any plans to introduce Boost navigation fumbling for 4.x? The ability to allocate links based on system role is really useful and no longer available in 4.x. 

Cheers
Stephen

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
