### ISSUE TITLE
Moodle 4.2.2

### ISSUE THREAD

**Issue by Katrina9999931** [moodleuulm/moodle-local_boostnavigation#116]
Hi,
will there're be a version of the plugin compatible with moodle 4.2.2. I installed it but it doesn't work.
Thank you

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
