### ISSUE TITLE
Collapse custom course nodes for users empties entire current course menu

### ISSUE THREAD

**Issue by pkgh** [moodleuulm/moodle-local_boostnavigation#16]
Hello,
Just begun using this great plugin - many thanks!
I have found it almost perfect for my needs, and will be happy to explore more:) . One glitch I have encountered though is with the  collapsecustomcoursenodesusers  setting. I have found that when I turn it on (after properly filling in the text area with a title line with link and children lines with links ), the contents of the current course box in the nav drawer competely disappear except for the heading with the course's shortname. On top of that, the breadcrumb navigation starts showing wrong paths..
The problem seems the affect the main course pages. Collapsing in this one context does not work as expected. I have tested on two almost identical sites with the same effect. In fact, it appears that after I tick the box for collapsing that user course menu, one course (the first one I go to after changing the setting) accepts the new collapsed menu, but all the other courses accessed from the same account do not: the menu is stripped to only the very course title (shortname) heading, while the breadcrumbs point to the path of the first course that I went to..   
My Moodle is 3.5.1, using plain Boost. My original settings on site 1  were:

removebadgescoursenode
removecompetenciescoursenode

insertcoursesectionscoursenode
insertactivitiescoursenode
insertresourcescoursenode
insertcustomcoursenodesusers

collapsecoursesectionscoursenode
collapsecoursesectionscoursenodedefault
collapseactivitiescoursenode
collapseactivitiescoursenodedefault

For the other attempt, on another site, I only entered the contents of the user menu (insertcustomcoursenodesusers) - as given below -  and ticked the collapse check box (collapsecustomcoursenodesusers):

Administration|/course/view.php?id={courseid}|||editingteacher
-Turn editing on|/course/view.php?id={courseid}&sesskey={sesskey}&edit=on|en||editingteacher
-Turn editing off|/course/view.php?id={courseid}&sesskey={sesskey}&edit=off|en||editingteacher
-Course administration|/course/admin.php?courseid={courseid}|en||editingteacher
-Edit course settings|/course/edit.php?id={courseid}|en||editingteacher
-Włącz tryb edycji|/course/view.php?id={courseid}&sesskey={sesskey}&edit=on|pl||editingteacher
-Wyłącz tryb edycji|/course/view.php?id={courseid}&sesskey={sesskey}&edit=off|pl||editingteacher
-Administracja kursem|/course/admin.php?courseid={courseid}|pl||editingteacher
-Edytuj Ustawienia|/course/edit.php?id={courseid}|pl||editingteacher 

I'd love to be able to fold that one extra menu I have created for the teachers. Hopefully you can get me on the right track or provide a fix if this is a bug. Many thanks.

PS I provide a screenshot illustrating the final effect:
![2018-08-22 21_04_47 - course_ testy aktywnosci __ activities tests - google chrome](https://user-images.githubusercontent.com/6607293/44485185-24cfe900-a650-11e8-8eab-342abfe4e59b.png)

**Comment by abias** [comment]
Hi @pkgh ,

thank you for creating this issue and sorry that it took me so long to answer.

I have to admit that I don't fully understand what you are reporting here as there are many facts and you seem to write about two different Moodle sites.

Could you please limit this issue to the issue which you summarized as "Collapse custom course nodes for users empties entire current course menu" and provide steps to reproduce (which settings did you set, what did you expect to see in the navigation, what did you really see), based on a plain installation of local_boostnavigation on Moodle 3.5? I will then be happy to check your problem here.

For any additional issue which does not belong to the "Collapse custom course nodes for users empties entire current course menu" problem, please create another issue here in Github.

Thanks,
Alex

**Comment by abias** [comment]
@pkgh, I am closing this issue as there was no feedback from you for one month.

If you come back to this issue, I will be happy to reopen it.

**Comment by pkgh** [comment]
Thanks, sorry, just had not time to re-investigate this. Only had a look at a couple of installs now, and the Moodles I mentioned in my original post (3.5.2 stable with a range of test-plugins installed) are still affected, while some other versions are not, apparently. So let's keep this issue buried down for now.
