### ISSUE TITLE
Editing Toggle

### ISSUE THREAD

**Issue by scotthardwick** [moodleuulm/moodle-local_boostnavigation#18]
Hello!
This is a very minor feature request and may not be useful to others, but....

Since we can add nodes to a course node section and now have access to placeholders {couresid} and {sesskey} my thought was to add the Turn Editing On/Off as a link into the boost navigation.  However, I would need to render it as two links right now so that one was 
/course/view.php?id={courseid}&sesskey={sesskey}&edit=off
and one was
/course/view.php?id={courseid}&sesskey={sesskey}&edit=on

Would there be some way to add a {edittoggle} placeholder that knew what the current status is and choose the appropriate opposite one?

Thanks!

**Comment by abias** [comment]
Hi Scott,

I have thought of this placeholder already when I added the placeholder feature initially, but didn't add it as we didn't need it here in Ulm and as I hesitated at first to add another mechanism to add placeholders to the node names.

Now, after https://github.com/moodleuulm/moodle-local_boostnavigation/commit/ad5627d8b28f73ac39d5b86df27988a705d2a673 and https://github.com/moodleuulm/moodle-local_boostnavigation/commit/67e7f08f5823cca6335915ec88f21078e2f5e309, you can now add a toggle editing node with something like
```
{editingtoggle}|{pagepath}&sesskey={sesskey}&edit={editingtoggle}
```

A new version with the patch will be published to the Moodle plugin repo soon.

Have fun!
Alex

**Comment by scotthardwick** [comment]
Thanks so much Alex!  This is wonderful news ;-)

All the best!
Scott
