### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by fabius24** [moodleuulm/moodle-local_boostnavigation#23]
Hi!

Just one quick question. I just installed your plugin (great plugin)
And I want to add an icon to my custom root nodes. Your documentation says I can use a Font Awesome icon but I don't understand how. Can you please write me an example of the correct "formula" for icons?

Thank you

**Comment by abias** [comment]
Hi @fabius24 ,

this is a custom node setting which we are using locally and which includes icons:
```
Site administration quicklinks|/admin/search.php|en
-List of users|/admin/user.php|||||fa-users
-Manage courses|/course/management.php|||||fa-graduation-cap
-Capability overview|/admin/tool/capability/index.php|||||fa-check-square-o
-Notifications|/admin/index.php|||||fa-wrench

```
I will add a similar example to the example section of the plugin's settings soon.

Hope this helps.

Cheers,
Alex
