### ISSUE TITLE
local_boostnavigation for Moodle 3.6

### ISSUE THREAD

**Issue by gushagelberg2** [moodleuulm/moodle-local_boostnavigation#26]
Hi,
will you be making this plugin available on Moodle 3.6?
Sure hope so because I really like it and use it on my productive 3.5 system. Not having this version is one reason I can't update to 3.6.
Best
Gus

**Comment by abias** [comment]
Hi Gus,

we have been running this plugin on a 3.6 development instance for several weeks now without real problems and also have made the latest feature developments (which were released today) on 3.5 and 3.6. However, it has not been released for 3.6 officially. This will happen within the next few weeks.

Cheers,
Alex

**Comment by gushagelberg2** [comment]
Hi Alex,
great news.
Thanks
Gus

**Comment by abias** [comment]
There you go: https://moodle.org/plugins/pluginversion.php?id=19170
Have fun :)

**Comment by gushagelberg2** [comment]
Great Alex,
Just installed it on 3.6 and it works perfectly.
Thanks
