### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by azrek** [moodleuulm/moodle-local_boostnavigation#27]
Hi,

First, thank you for the plugin.

We are getting notices when we run the unit tests for this plugin:

PHP Notice:  Undefined property: stdClass::$insertcustomnodesusers in /moodle/local/boostnavigation/lib.php on line 678

Notice: Undefined property: stdClass::$insertcustomnodesusers in /moodle/local/boostnavigation/lib.php on line 678
PHP Notice:  Undefined property: stdClass::$insertcustomnodesadmins in /moodle/local/boostnavigation/lib.php on line 679

Notice: Undefined property: stdClass::$insertcustomnodesadmins in /moodle/local/boostnavigation/lib.php on line 679
PHP Notice:  Undefined property: stdClass::$insertcustomcoursenodesusers in /moodle/local/boostnavigation/lib.php on line 680

Notice: Undefined property: stdClass::$insertcustomcoursenodesusers in /moodle/local/boostnavigation/lib.php on line 680
PHP Notice:  Undefined property: stdClass::$insertcustomcoursenodesadmins in /moodle/local/boostnavigation/lib.php on line 681

Notice: Undefined property: stdClass::$insertcustomcoursenodesadmins in /moodle/local/boostnavigation/lib.php on line 681
PHP Notice:  Undefined property: stdClass::$insertcustombottomnodesusers in /moodle/local/boostnavigation/lib.php on line 682

Notice: Undefined property: stdClass::$insertcustombottomnodesusers in /moodle/local/boostnavigation/lib.php on line 682
PHP Notice:  Undefined property: stdClass::$insertcustombottomnodesadmins in /moodle/local/boostnavigation/lib.php on line 683

Notice: Undefined property: stdClass::$insertcustombottomnodesadmins in /moodle/local/boostnavigation/lib.php on line 683

Running on the following systems:
**Moodle: 3.6.1**
$version  = 2018120303.06;
$release  = '3.6.3+ (Build: 20190328)'; 

**boostnaviation plugin:**
$plugin->version = 2019031301;
$plugin->release = 'v3.6-r1';

DB: Postgres (actually - n/a as this will have the same issue with mysql)
OS: Linux - Ubuntu 18.04
PHP 7.2.10

Thanks for your time.

Cheers,
Ghada

**Comment by azrek** [comment]
An update, updated plugin to:

$plugin->version = 2019032800;
$plugin->release = 'v3.6-r2';

Getting the same thing.

Cheers.

**Comment by abias** [comment]
Hi @azrek ,

thank you for reporting this. I am afraid that a flaw has sneaked in when we implemented the support for custom node icons recently.

This has now been fixed in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/ba1fa58eb1cd36b8952fe6f901299ef5021c348b

Cheers,
Alex
