### ISSUE TITLE
Possible to add next and previous course in navigation

### ISSUE THREAD

**Issue by jskoenderman** [moodleuulm/moodle-local_boostnavigation#45]
Hello @abias,

I really like your plugin; very helpful.
I have a question: Is it possible to add to the navbar links to the next course and the previous course when I am at a course page?
So I have a categorie with 16 courses; when I'm in course 3, I would like to see a link refering to the previous course (2) and a link to the next course (4). Is that feasible with custom css? And if yes, what code do I need to use?

Thank you.

With kind regards,
Jorine Koenderman

**Comment by abias** [comment]
Hi @jskoenderman ,

do you mean something like this:
![Course__Alex__Sandkasten](https://user-images.githubusercontent.com/1092118/63768244-00949100-c8d0-11e9-845f-ab1403505697.png)
(please ignore the styling of the nav drawer and focus on the "Next course" and "Previous course" nodes).

This does not work out of the box currently, but I think creating something like this should be possible with the plugin's existing placeholder framework. Unfortunately, I don't see a definite natural result for the question what the next and the previous course is. Your expectation is the get the next / prev course in the same category. Others might expect to get the next / prev course based on the course start date.

Additionally, we don't have a real need for this functionality at the moment, so we can't implement this at the moment. If you have development ressources, we are happy to review a pull request.

Cheers,
Alex

**Comment by abias** [comment]
As there hasn't been any additional answer how these buttons should behave in real usage and as we don't have a need for this feature here, I am going to close this issue now.

Cheers,
Alex
