### ISSUE TITLE
Course node sections icon is not correct

### ISSUE THREAD

**Issue by adpe** [moodleuulm/moodle-local_boostnavigation#52]
Why did you don't set an icon for this root node? It looks really weird:

![image](https://user-images.githubusercontent.com/9467708/71164029-8d33d800-224e-11ea-876c-687f6fdcface.png)

**Comment by abias** [comment]
Hi Adrian,

This node doesn't have an icon by purpose. I mainly built it as a heading for a collapsible "sections" section. If you look at Ulm's navigation (on the right), you will notice what I mean:

![sections](https://user-images.githubusercontent.com/1092118/73776810-b7067700-4788-11ea-8d5a-626481223eff.png)

In this usage scenario, an icon would be counterproductive. The same goes for the activities node, for the my courses node and for custom parent nodes.

So, if you want to add an icon to this node - and I would agree that there might be reasons for doing that in other usage scenarios than ours, you should

* Build it as a setting
* Apply the same behaviour to the other three mentioned nodes as well.

Based on this feedback, I am closing #53 for now and will be happy to get another contribution from you which addresses my feedback :)

Thanks,
Alex

**Comment by adpe** [comment]
Thanks for your feedback @abias 

You're right and I understand your scenario as well. In our case we have the opposite, the sections underneath have no icons and only the heading has an icon.

I'll look to rework my code and make a new request.

Greets,
Adrian

**Comment by adpe** [comment]
Hi @abias 

I reworked it as you suggested and would be happy to hear what you think about this implementation.

I know we have other priorities at the moment, but I think this should not stop other already ongoing, nearby finished work.

Cheers,
Adrian

**Comment by abias** [comment]
This issue was closed by #57.
