### ISSUE TITLE
Remove participants node

### ISSUE THREAD

**Issue by pjonker** [moodleuulm/moodle-local_boostnavigation#54]
Hi Alexander, thanks very much for this plugin! It is very helpful and we use it all the time. I found one issue with local_boostnavigation | removeparticipantscoursenode. In the description you mention it should not cause any problem but I found the following. It definitely removes the Participants node for regular users which is good. However when being an admin I want to enrol participants through Course Administration / More / Users / Enrolled users (/user/index.php?id=XX). Normally the breadcrumb stays intact and I can go back to the course using the breadcrumb. When the participants node is being removed the breadcrumb becomes Dashboard / Site pages / Participants and I can not use the breadcrumb to navigate back to the course. Could you have a look at this issue and let me know if it could be solved? Already tried to hide Participants node through css but cannot pin-point the class.

**Comment by abias** [comment]
Hi @pjonker ,

thank you for raising this issue.

There are two technical approaches to remove a node from the nav drawer:
* The "soft" one is to set its showinflatnavigation attribute to false which results in the node not being shown in the nav drawer but being left in the navigation tree. This approach is preferred by this plugin, but does not work for all nodes.
* The "hard" one is to remove the node from the navigation tree which results in the node not being visible anywhere it is used - which includes the breadcrumb.

Regarding the removeparticipantscoursenode, the hard approach is used which means that the harm on the breadcrumb is as expected.

I think the behaviour which you are seeing is collateral damage. I don't see a real solution for this, only even more nasty workarounds letting the node stay for the admin or something like that.

As we don't use the removeparticipantscoursenode setting here and I had only added it upon request from a Moodle partner and to complete the list of Moodle core nodes which are available to be removed, I can't do anything about this.

Sorry,
Alex

**Comment by pjonker** [comment]
Hello Alex,

Don't know if it is of any help for you but we found a way to remove the Participants node from the Navdrawer without destroying the breadcrumb. We just added the piece below to the CSS of the site.

#nav-drawer [data-key="participants"] {display: none;}

Peter Jonker
