### ISSUE TITLE
Boost left navigation theme issue

### ISSUE THREAD

**Issue by Lina-LI-Na** [moodleuulm/moodle-local_boostnavigation#6]
Dear Alexander,
Thanks a lot for your great contribution in developing the boost navigation fumbling plugin. I'm a big fan of your plugin. Our University is using the Boost Campus plugin and the Boost Navigation Fumbling plugin. Everything is very nice, but just a little issue in the IE browser. I have attached the screenshot:
![Uploading screenshot of left navigation.PNG…]
If the attached screenshot cannot display, please use the below URL to see the screenshot:
https://connect.xjtlu.edu.cn/user/na-li/boost-left-navigation-theme-issue 

I've tested that the theme are working fine in the following browsers:
1. chrome, firefox, safari on Mac
2. chrome, firefox on Windows computer
3. firefox on Android phone

The theme issue only occurred in IE browser on Windows computer. We are using IE version 11.
We will be really appreciate it if you could help to fix this problem.
Many thanks.
Best wishes,
Lina

**Comment by abias** [comment]
Hi Lina,

thank you for your detailed bug report.

I have to admit that we don't regularly test on IE, so bugs might go unnoticed in this browser.

To reproduce and solve the bug, I would need to know:
* Which version of Moodle you are running
* Which version of theme_boost_campus you are running
* Which version of local_boostnavigation you are running
* The complete list of settings on local_boostnavigation which is configured on /admin/settings.php?section=local_boostnavigation
* If this problem also persists if you switch your theme to theme_boost (not theme_boost_campus).

Thanks,
Alex

**Comment by Lina-LI-Na** [comment]
Hi Alex,
My last email has not sent out to your mail box because the attached screenshot is too big.
I’ve removed the screenshot, hopefully you can receive this email. I will send you the screenshot in a separate email.
Thanks.

Best wishes,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Na Li (FHEA),
Educational Technologist,
Educational Development Unit, ILEAD,
Xi’an Jiaotong-Liverpool University (XJTLU),

Phone: (0086) 0512-88161279
E-mail: na.li@xjtlu.edu.cn
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

From: NaLi
Date: Wednesday, March 7, 2018 at 3:09 PM
To: moodleuulm/moodle-local_boostnavigation, moodleuulm/moodle-local_boostnavigation
Cc: Author, Roland Sherwood
Subject: Re: [moodleuulm/moodle-local_boostnavigation] Boost left navigation theme issue (#6)

Hi Alex,
Thank you for your prompt response. Really appreciate it.
Following information in red is for your reference:


  *   Which version of Moodle you are running :2017051504    3.3.4 (Build: 20180115)
  *   Which version of theme_boost_campus you are running : 2018020700 v3.3-r3
  *   Which version of local_boostnavigation you are running : 2018022001 v3.3-r1
  *   The complete list of settings on local_boostnavigation which is configured on /admin/settings.php?section=local_boostnavigation  (please refer to the attached screenshots)
  *   If this problem also persists if you switch your theme to theme_boost (not theme_boost_campus). (The problem did not persist when I switch my theme to theme_boost)

Thanks.

Best wishes,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Na Li (FHEA),
Educational Technologist,
Educational Development Unit, ILEAD,
Xi’an Jiaotong-Liverpool University (XJTLU),

Phone: (0086) 0512-88161279
E-mail: na.li@xjtlu.edu.cn<mailto:na.li@xjtlu.edu.cn>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

From: Alexander Bias
Reply-To: moodleuulm/moodle-local_boostnavigation
Date: Wednesday, March 7, 2018 at 2:31 PM
To: moodleuulm/moodle-local_boostnavigation
Cc: NaLi, Author
Subject: Re: [moodleuulm/moodle-local_boostnavigation] Boost left navigation theme issue (#6)


Hi Lina,

thank you for your detailed bug report.

I have to admit that we don't regularly test on IE, so bugs might go unnoticed in this browser.

To reproduce and solve the bug, I would need to know:

  *   Which version of Moodle you are running
  *   Which version of theme_boost_campus you are running
  *   Which version of local_boostnavigation you are running
  *   The complete list of settings on local_boostnavigation which is configured on /admin/settings.php?section=local_boostnavigation
  *   If this problem also persists if you switch your theme to theme_boost (not theme_boost_campus).

Thanks,
Alex

**Comment by Lina-LI-Na** [comment]
Hi Alex,
Attached are the screenshots to show all the boost navigation’s settings. Hopefully you can receive them now.
Best wishes,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Na Li (FHEA),
Educational Technologist,
Educational Development Unit, ILEAD,
Xi’an Jiaotong-Liverpool University (XJTLU),

Phone: (0086) 0512-88161279
E-mail: na.li@xjtlu.edu.cn
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

From: NaLi
Date: Wednesday, March 7, 2018 at 4:15 PM
To: moodleuulm/moodle-local_boostnavigation, moodleuulm/moodle-local_boostnavigation
Cc: Author, Roland Sherwood
Subject: Re: [moodleuulm/moodle-local_boostnavigation] Boost left navigation theme issue (#6)

Hi Alex,
My last email has not sent out to your mail box because the attached screenshot is too big.
I’ve removed the screenshot, hopefully you can receive this email. I will send you the screenshot in a separate email.
Thanks.

Best wishes,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Na Li (FHEA),
Educational Technologist,
Educational Development Unit, ILEAD,
Xi’an Jiaotong-Liverpool University (XJTLU),

Phone: (0086) 0512-88161279
E-mail: na.li@xjtlu.edu.cn<mailto:na.li@xjtlu.edu.cn>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

From: NaLi
Date: Wednesday, March 7, 2018 at 3:09 PM
To: moodleuulm/moodle-local_boostnavigation, moodleuulm/moodle-local_boostnavigation
Cc: Author, Roland Sherwood
Subject: Re: [moodleuulm/moodle-local_boostnavigation] Boost left navigation theme issue (#6)

Hi Alex,
Thank you for your prompt response. Really appreciate it.
Following information in red is for your reference:


  *   Which version of Moodle you are running :2017051504    3.3.4 (Build: 20180115)
  *   Which version of theme_boost_campus you are running : 2018020700 v3.3-r3
  *   Which version of local_boostnavigation you are running : 2018022001 v3.3-r1
  *   The complete list of settings on local_boostnavigation which is configured on /admin/settings.php?section=local_boostnavigation  (please refer to the attached screenshots)
  *   If this problem also persists if you switch your theme to theme_boost (not theme_boost_campus). (The problem did not persist when I switch my theme to theme_boost)

Thanks.

Best wishes,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Na Li (FHEA),
Educational Technologist,
Educational Development Unit, ILEAD,
Xi’an Jiaotong-Liverpool University (XJTLU),

Phone: (0086) 0512-88161279
E-mail: na.li@xjtlu.edu.cn<mailto:na.li@xjtlu.edu.cn>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

From: Alexander Bias
Reply-To: moodleuulm/moodle-local_boostnavigation
Date: Wednesday, March 7, 2018 at 2:31 PM
To: moodleuulm/moodle-local_boostnavigation
Cc: NaLi, Author
Subject: Re: [moodleuulm/moodle-local_boostnavigation] Boost left navigation theme issue (#6)


Hi Lina,

thank you for your detailed bug report.

I have to admit that we don't regularly test on IE, so bugs might go unnoticed in this browser.

To reproduce and solve the bug, I would need to know:

  *   Which version of Moodle you are running
  *   Which version of theme_boost_campus you are running
  *   Which version of local_boostnavigation you are running
  *   The complete list of settings on local_boostnavigation which is configured on /admin/settings.php?section=local_boostnavigation
  *   If this problem also persists if you switch your theme to theme_boost (not theme_boost_campus).

Thanks,
Alex

**Comment by Lina-LI-Na** [comment]
Hi Alex,
How are you? Hope everything is going well with you.
Since the default browser of our University's computers is IE, more and more teachers are complaining about the theme problem. I know you are very busy and sorry to bother you for this issue.
Is there any update about this?
Many thanks.
  

Best wishes,
Lina

**Comment by abias** [comment]
Hi Lina,

sorry for the lack of feedback on my side. Yes, I am constantly busy, but this shouldn't keep me from fixing bugs.

Here is my feedback:
* I could _not_ reproduce this problem on an up-to-date Moodle 3.4.2+ instance with local_boostnavigation v3.4-r3 and theme_boost_campus v3.4-r4 which we are currently working on.
* I could reproduce this problem on a legacy Moodle 3.2.8 with local_boostnavigation v3.2-r18 
 and theme_boost_campus v3.2-r7 which we are still running for another few weeks.
* Between local_boostnavigation versions v3.3 and v3.4, there was a change in the way how the icons to collapse the nodes are displayed. I expect that the old way in v3.3 triggered this odd behaviour in IE and the new way does not.
* As this problem does only appear in a legacy version of our plugin, I won't be able to fix it due to our Moodle release support policy (see https://github.com/moodleuulm/moodle-local_boostnavigation#moodle-release-support).
* https://github.com/moodleuulm/moodle-local_boostnavigation#moodle-release-support also tells you that you could backport a current plugin version to a legacy Moodle at your own risk. In this particular case, please be warned that you would have to backport the latest version of local_boostnavigation _and_ theme_boost_campus to Moodle 3.3 as there were some changes in both plugins which are directly connected. I am not sure if this will work without side-effects.
* As a last note, I have reproduced this problem on a MS Surface device with IE 11.0.9600.18817, but I was not able to reproduce it on a virtual machine with IE 11.2068.14393.0. I am no Windows / IE expert, but perhaps it might help just to upgrade your IE to the latest version.

Sorry, that I can't give you any better news.

Thanks,
Alex

**Comment by Lina-LI-Na** [comment]
Hi Alex,
Many many thanks for all your efforts of reproducing the problem in different environment and the detailed explanation. We really appreciate your kind help. We will upgrade Moodle this summer and will also upgrade the two plugins according to your suggestion. We will let you know then.
Thanks again. Have a nice day.
Best wishes,
Lina
