### ISSUE TITLE
Add MUC cache to cohort membership

### ISSUE THREAD

**Issue by Anupamatd** [moodleuulm/moodle-local_boostnavigation#60]
Improve check for cohort membership by adding MUC cache.

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
