### ISSUE TITLE
Error on user logs page when 'Remove Participants node' enabled

### ISSUE THREAD

**Issue by zpottie** [moodleuulm/moodle-local_boostnavigation#62]
Hi there,

When the setting `removeparticipantscoursenode` is enabled, an error is thrown when accessing a user's logs in a course. E.g. when on the page `wwwroot/report/log/user.php?id=3&course=3&mode=all` the error is thrown:
![RemoveParticipantsEnabled](https://user-images.githubusercontent.com/9076608/80040577-7b40a980-854e-11ea-9934-e53bca67d143.png)

I tried creating a fix to hopefully help you guys out too - and us, as several of our client use this (awesome) plugin. You can see pull request #61 for more info and proposed fixes.

Thanks again,
Zander

**Comment by DKSteffensen** [comment]
Just want to mention we had an issue with this too. Same problem.

**Comment by abias** [comment]
This was fixed by #61
