### ISSUE TITLE
error : moove theme compatibility

### ISSUE THREAD

**Issue by CappiLucky** [moodleuulm/moodle-local_boostnavigation#69]
Hello @abias , 
First, thanks you for this plugin !

Then, I would like to inform you that all the functionality of the plugin does not work with the Moove theme : 
- the icon change is not done
- and the hierarchy / tree structure of tabs does not fall into place

I am aware of the work you have done, this is not a criticism but a note to help you improve this plugin as well as possible.

Have a good day, 
CappiLucky

**Comment by abias** [comment]
Hi @CappiLucky ,

please let me point you to https://github.com/moodleuulm/moodle-local_boostnavigation/blob/master/README.md#theme-support where we wrote:

> This plugin is developed and tested on Moodle Core's Boost theme. It should also work with Boost child themes. However, we can't support any other theme than Boost.

Yes, Moove is a Boost child theme. But obviously, they did change something in the nav drawer which overrides the changes of this plugin.

I think I can say that we can't do much about this as we don't use this theme.

However, if you want to reach out to the maintainers of the Moove theme and they give you some clear proposal what local_boostnavigation should do different, then we could re-triage this issue again.

Thanks for your understanding.

Cheers,
Alex
