### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by sharpchi** [moodleuulm/moodle-local_boostnavigation#7]
I'm sure you're on the case. I see that you now store user_preferences for some of the expandable components. These, for us at least, would need to be GDPRd at some point. Is that on the roadmap?

**Comment by abias** [comment]
Hi Mark,

thanks for this question.

We are in the process of working through the GDPR challenges and updating our plugins will be one of the topics we will surely tackle. I can tell you that it will be done as we are also directly affected by GDPR, but I can't tell you yet how many days before the 25th may deadline it will be delivered...

Thanks,
Alex

**Comment by sharpchi** [comment]
No worries. We're all under the same challenges.

**Comment by abias** [comment]
Hi Mark,

this is now implemented in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/3d5d03e3a637378545931719ef4cb69467ce1f33 and will be available in the Moodle plugin repo in a few minutes.

Cheers,
Alex
