### ISSUE TITLE
Add ability to remove new Moodle 3.9 Content bank link

### ISSUE THREAD

**Issue by nadavkav** [moodleuulm/moodle-local_boostnavigation#70]
Please see if you can add the ability to remove the new Moodle 3.9 Content bank from the root navigation links.

**Comment by abias** [comment]
Hi @nadavkav ,

the release of this plugin for 3.9 is currently scheduled and the removal of the content back link is on the ToDo list.

I will handle the pull request in #71 which is a great basis for my work.
Please stay tuned.

Cheers,
Alex

**Comment by nadavkav** [comment]
Hi @abias 
I am attaching a patch that solved this issue. please review.
[add_ability_to_remove_content_bank.patch.txt](https://github.com/moodleuulm/moodle-local_boostnavigation/files/5286430/add_ability_to_remove_content_bank.patch.txt)

Nadav

**Comment by nadavkav** [comment]
Me bad, just now looked into #71 and it seem like a much better solution then the patch I previously uploaded. so please disregard it.

**Comment by abias** [comment]
Closing as requested in favour of #71 
The 3.9 release is finally published and the removal of the content bank node is possible now with the 3.9 release.

**Comment by nadavkav** [comment]
Thank you @abias ! looks great :smile:
