### ISSUE TITLE
collapsemycoursesnodesession not working

### ISSUE THREAD

**Issue by ylberukzmaili** [moodleuulm/moodle-local_boostnavigation#73]
collapsemycoursesnodesession is disabled in our Moodle so it should keep the collapse parameter while navigating into Moodle but it dowsn't work.

When I collapse the My courses node and I go to another Moodle page, it's not collapsing anymore. I have to collapse everytime I change or refresh a page.

**Comment by abias** [comment]
Hi @ylberukzmaili ,

Can you please tell me:
* Which Moodle core version are you using?
* Which version of the plugin are you using?
* Does this only happen for the My courses node or also for other collapsed node, for example the activities nodes?

Thanks,
Alex

**Comment by abias** [comment]
Closing as there wasn't any feedback anymore.
