### ISSUE TITLE
Problem with links under the navigation menu

### ISSUE THREAD

**Issue by ralf-krause** [moodleuulm/moodle-local_boostnavigation#75]
When the Moodle window is small as you will have it on smartphones or tablets then a click on the boost navigation items is sent to the second layer. A click on "My Courses" does not react with the boost menu.

The screenshot shows the Boost menu and the Unilabel carousel. The picture in the Unilabel is linked to a course section.

<img width="697" alt="boost nav and links" src="https://user-images.githubusercontent.com/27956839/94360309-8c1cba80-00ac-11eb-91f1-11ebac6f4dec.png">

**Comment by ralf-krause** [comment]
Sorry, I think that it will be a problem with the unilabel plugin. I also get the problem without the plugin local_boostnavigation.

**Comment by abias** [comment]
All right. Thanks for confirming that this is not a problem of this plugin, Ralf
