### ISSUE TITLE
Possible compatibility with FilterCodes

### ISSUE THREAD

**Issue by argwallace** [moodleuulm/moodle-local_boostnavigation#76]
When creating some of the menus, FIlterCodes are not always recognized. I understand it may not be in the scope of this plugin to work with FilterCodes but it would provide even more customization and flexibility when adding menus. One example would be that certain menus I would like to be hidden when the user is not logged. FilterCodes allows for this but it is n't recognized by FBN. FilterCodes works on other areas so I suggest this in hopes that it is a simple fix that could greatly enhance the usability of this wonderful plugin. Thanks for considering it.
Stephen

**Comment by abias** [comment]
Hi @argwallace , 

to be able to understand what you are really looking for, I would like to ask you to write some steps to reproduce (see https://docs.moodle.org/310/en/How_to_add_steps_to_reproduce_to_a_bug_report#Example_of_test_steps for an example) based on a fresh Moodle installation.

Thanks,
Alex

**Comment by abias** [comment]
Hi @argwallace ,

I am closing this now as you didn't answer anymore.
However, don't hesitate to comment again as soon as you are able to add some more details to your request.

Cheers,
Alex
