### ISSUE TITLE
Exclude section 0 from section navigation

### ISSUE THREAD

**Issue by chiaravicere** [moodleuulm/moodle-local_boostnavigation#77]
This is a proposal to help people who don't want to use the "section 0" default in all Moodle courses: to implement an option to exclude section 0 from course node "sections".
A simple "display none" to the node id causes a flashing at page reload, obviously.

**Comment by abias** [comment]
Hi @chiaravicere ,

the "Section 0" navigation node (which is labeled as "General" at least in theme_topics) does not appear until there is at least one activity added to section 0. This is Moodle standard behaviour. Thus, teachers who don't fill this section don't have the navigation node in their course.

Additionally, the code for handling the section nodes is already quite tricky in local_boostnavigation and I refrain from making it more trickier (and error-prone).

So I would like to thank you for this proposal, but would close it as "Won't do" for now.

Cheers,
Alex
