### ISSUE TITLE
Remove root node "Home" also removes <nav> tag

### ISSUE THREAD

**Issue by FloMiLe** [moodleuulm/moodle-local_boostnavigation#78]
Normally, there are three `<nav>` tags in the nav bar: for the course, the main one for navigation, and the third for settings.

When one checks the setting Remove root node "Home", apparently the closing of the first and the opening of the second `<nav>` tag get lost. The result is that the gap above the Dashboard button is removed.

**Comment by abias** [comment]
I agree that this can happen if you set $CFG->defaulthomepage = Site and then decide to remove the "Home" navigation node.
Similar things can happen if you set $CFG->defaulthomepage = Dashboard and then decide to remove the "Dashboard" node. 

This is something which can't be prevented and which was already discussed in a similar scenario in #40.

If you want to remove the Home navigation node, then please check if you can set $CFG->defaulthomepage = Dashboard.

Cheers,
Alex
