### ISSUE TITLE
Can I hide custom root nodes in course

### ISSUE THREAD

**Issue by nguyenlt1506** [moodleuulm/moodle-local_boostnavigation#79]
Hi there, 
Can you help me to hide all custom root nodes when i enter in a course.
Thank you !
![tempsnip](https://user-images.githubusercontent.com/37679617/97133797-b762fa00-177d-11eb-9e7e-d457c99205bd.png)

**Comment by abias** [comment]
Hi @nguyenlt1506 ,

I am sorry, but this is neither possible at the moment nor planned to be implemented anytime soon.
The custom root nodes and custom bottom nodes are added to the nav drawer on all pages, regardless if you are viewing a course or not.

Cheers,
Alex
