### ISSUE TITLE
Collapse root node "My courses" setting not working - Moodle 3.8.6+

### ISSUE THREAD

**Issue by iandavidwild** [moodleuulm/moodle-local_boostnavigation#80]
I've had a quick look through the code and it seems the class name the JavaScript is looking for is not in the tree? Please see attached screen grab.

![Screenshot_1](https://user-images.githubusercontent.com/2386283/104122457-0102c000-533d-11eb-83ed-6c859465afdd.jpg)

**Comment by abias** [comment]
Hi @iandavidwild ,

first, please note that we don't support Moodle 3.8 anymore with this plugin - see https://github.com/moodleuulm/moodle-local_boostnavigation/blob/master/README.md#moodle-release-support for details.

Additionally, looking at the screenshot, I have the impression that you are not looking at the Boost navigation drawer at all but at the "Navigation" block - which can still be added to Moodle, but which is unnecessary as we have the Boost navigation drawer today and which this plugin is not touching at all.

Thus, I am closing this issue now.

Cheers,
Alex
