### ISSUE TITLE
course categories

### ISSUE THREAD

**Issue by fabianwinda** [moodleuulm/moodle-local_boostnavigation#81]
Hi, first of all thank you for your gorgeous plugin, its the perfect addition to the standard boost navigation bar!
I wonder if theres a way to show all course categories as a node, similiar to the old navigation block. Just for Administrators to quickly navigate between many courses. 
I have read your readme but I can't find a way to accomplish it. 

Thank you for your help in advance

**Comment by abias** [comment]
Hi @windadev1 ,

I am sorry, but there is no possibility to achieve this goal currently and there isn't a plan to implement this either.

Cheers,
Alex
