### ISSUE TITLE
collapsecustomnodesusersdefault does not work on 3.9.2

### ISSUE THREAD

**Issue by jmeagherPT** [moodleuulm/moodle-local_boostnavigation#82]
I have a collapsible custom root node for the nav drawer and have selected the "Collapse custom root nodes for all users by default" selected.

![image](https://user-images.githubusercontent.com/79484897/108779115-69e07900-7534-11eb-8a2a-81fb177318bb.png)

The root node requires the Authenticated User role in order for it to appear. However, when I log in as a test account I have created the custom root node is expanded upon login as well as on my admin account.

![image](https://user-images.githubusercontent.com/79484897/108779472-eb380b80-7534-11eb-8ea1-b214f696b9c3.png)

The Useful Links node should be collapsed by default with the links below it hidden, but it is not.

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
