### ISSUE TITLE
Active class not not enabled on bottom nodes

### ISSUE THREAD

**Issue by easypony** [moodleuulm/moodle-local_boostnavigation#83]
Hello

I have added 4 custom bottom nodes 2 external and 2 internal. The first internal node when clicked shows the page and the classes added to that link are `list-group-item list-group-item-action active active_tree_node ` all good.

When the node below is clicked the active classes stay on the top node and do not show on the clicked (real) "active" node.
The classes on the active node are `list-group-item list-group-item-action  `

Cheers
Steve

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
