### ISSUE TITLE
Default user roles not being checked

### ISSUE THREAD

**Issue by BKaifer** [moodleuulm/moodle-local_boostnavigation#84]
It doesn't look like the plugin checks the default role for all users when checking system user roles. The default role for users set in the Moodle User Policies menu is not being added to the list of roles the user has in the function [local_boostnavigation_user_has_role_on_system](https://github.com/moodleuulm/moodle-local_boostnavigation/blob/master/locallib.php#L690).

Is there a reason why this wasn't done or is it a bug/oversight?

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
