### ISSUE TITLE
Extra wrong crumb trail nodes can be added, possibly admin tree specific

### ISSUE THREAD

**Issue by brendanheywood** [moodleuulm/moodle-local_boostnavigation#85]
To reproduce:

/admin/settings.php?section=local_boostnavigation_customrootnodes

Add a node like:

-Enable/Disable Account Methods|/admin/settings.php?section=manageauths

Then visit a page such as:

/admin/settings.php?section=outgoingmailconfig

And now the crumb trail on this page looks like:

1. Home
2. Admin tools
3. Enable/Disable Account Methods  <<---- this should not be here
4. Server
5. Email
6. Outgoing mail configuration

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
