### ISSUE TITLE
System role "user" not working

### ISSUE THREAD

**Issue by amjohnson46** [moodleuulm/moodle-local_boostnavigation#86]
I'm not sure if this is related to issue #84, but I was trying to make a node only visible after logging in. The system role "Authenticated user" (shortname "user") should be just right for that. According to the Moodle documentation: "When a user logs in, they are automatically assigned the role of authenticated user." I tried putting "user" in the system role option, but the node is just gone and doesn't appear after logging in. I then noticed my authenticated user role was not explicitly set to the "System" context, so I added that check mark, but nothing changed. I'm using Moodle 3.9.5 and Boost navigation fumbling v3.9-r6 (2020112303).

Here is the custom root node code I tried:
My certificates|/mod/customcert/my_certificates.php?userid={userid}|en|||user||fa-certificate

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
