### ISSUE TITLE
Content Bank not being made active

### ISSUE THREAD

**Issue by hugoacfs** [moodleuulm/moodle-local_boostnavigation#87]
Thank you for adding a new feature 8cfc30a to enable content bank to sit under the course nodes section.

I'm moving to Moodle 3.9 soon and I will be using this feature, but I noticed that when selected, users do not see Content Bank highlighted as active (see screenshot).

![image](https://user-images.githubusercontent.com/47332377/118515689-83f1b800-b72d-11eb-990e-5b53fde96f48.png)

I wondered whether it would be possible to make it active, and not the course node parent? I tried adding something like this after [line 474 in the lib.php file](https://github.com/moodleuulm/moodle-local_boostnavigation/blob/95192f6903cf00dd23bfc8014ccf8a37f9d784b2/lib.php#L474):
```php
// Make the content bank tab active.
if ($PAGE->pagetype == 'contentbank') {
    $contentbanknode->make_active();
}
```

This is what I got:
![image](https://user-images.githubusercontent.com/47332377/118516343-214cec00-b72e-11eb-9592-a156cb61a988.png)

I wonder if you know a way of making it work so that the 'XS_COURSE' tab is no longer active, and the breadcrumbs do not show a repeat of 'Content Bank'.

I hope this is useful.
Regards,
Hugo

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
