### ISSUE TITLE
Add a course admin node in navdrawer.

### ISSUE THREAD

**Issue by cellule-tice** [moodleuulm/moodle-local_boostnavigation#9]
Hi there,
Many teachers in my institution ask for a direct access to course admin page in the navdrawer. 
What do you think? (one click less than through the course gear icon)

**Comment by abias** [comment]
Hi @cellule-tice ,

even though you have closed this issue yourself, you might want to have a look at https://github.com/moodleuulm/moodle-local_boostnavigation/issues/10 where we implemented your request.

Cheers,
Alex
