### ISSUE TITLE
Showing nodes when unauthenticated?

### ISSUE THREAD

**Issue by frumbert** [moodleuulm/moodle-local_boostnavigation#95]
Is it possible to show nodes when a user is not yet authenticated, and hide them again after they are authenticated?

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
