### ISSUE TITLE
Tenant specific links

### ISSUE THREAD

**Issue by Jaron026** [moodleuulm/moodle-local_boostnavigation#96]
We use this plugin for all our customers and the plugin is great. Lot of out customers are using Moodle Workplace and they want tenant specific links.
Is this something you are planning to work on? For example:
Random link|course_1||||Tenant1

**Comment by christianwolters** [comment]
Hi @Jaron026,

just my two cents: as far as I know none of the previous contributors uses Workplace or has knowledge of its specific plugins, yet.

Therefore, even if one would provide a PR for this, this would certainly complicate the maintenance for this plugin.

Best Regards
Christian

**Comment by Jaron026** [comment]
Hi Christian,

Thanks for the quick reply
Well that seems to be enough to close the ticket. I'll see if we can create another local that just has the tenant specific option.

Best regards,

Jaron
