### ISSUE TITLE
Activities node showing to unauthorised users

### ISSUE THREAD

**Issue by pkgh** [moodleuulm/moodle-local_boostnavigation#97]
The Activities node, along with the icons of all the activity types used in a course, are leaked to:

- unenrolled users attenpting to enter a course via a link
- users logged in as guests (even though guests have no access to the course)

Tested on 
Moodle 3.9.8 and BNF v3.9-r6 2020112303

(Same behaviour observed on older Moodle 3.6.10 and BNF v3.6-r7 2019061500)

The problem also concerns the "Resources" item.
The problem does not affect the "Sections" node.

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
