### ISSUE TITLE
Custom course nodes showing to suspended and inactive course participants

### ISSUE THREAD

**Issue by pkgh** [moodleuulm/moodle-local_boostnavigation#98]
Custom course nodes  (even if precise course roles are duly listed for access - which I believe should be irrelevant here) "leak" to students, non-editich teachers or teachers who have been suspended or deactivated in a course,. Such users, when attempting to join the course again from a link, can see in the menu all the custom nodes added in the insertcustomcoursenodesusers field of FBN settings.

E.g. suspended teachers will even see the "Turn editing on" button in the menu..

My precise settings for Role|SystemRole|Boolean for the custom course nodes in question are

editingteacher,teacher,student|admin,manager|OR

Tested on
Moodle 3.9.8 and BNF v3.9-r6 2020112303

**Comment by abias** [comment]
This plugin has finally reached end of life now and will not be upgraded to Moodle 4.x.

I would like to invite you to have a look at our [Moodle 4 theme theme_boost_union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) which supports several aspects of this plugin's feature set and is actively maintained and extended. Thank you for your understanding.

Against this background, I will close this issue.
